espaco = " "
print(f"{espaco*7}A")
print(f"{espaco*6}B B")
print(f"{espaco*5}C   C")
print(f"{espaco*4}D     D")
print(f"   E       E")
print(f"{espaco*4}D     D")
print(f"{espaco*5}C   C")
print(f"{espaco*6}B B")
print(f"{espaco*7}A")
